server:
  port: 8890

spring:
  application:
    name: springboot-admin  #服务名
  profiles:
    active:
      - secure

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

eureka:
  client:
      registryFetchIntervalSeconds: 30
      serviceUrl:
        defaultZone:http: http://${spring.cloud.client.ip-address}:8761/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 30
      health-check-url-path: /actuator/health
      preferIpAddress: true   #将IP注册到Eureka Server上，默认主机名。
      instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点(/info,/health,/env,/beans)
        exclude:
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: insecure

---

spring:
  profiles: secure
  security:
    user:
      name: jwx
      password: jwx

eureka:
  instance:
    metadata-map:
      user.name: jwx
      user.password: jwx

