server:
  port: 8888

#运行暴露端点信息
endpoints:
  shutdown:
    enabled: true

eureka:
  client:
      serviceUrl:
        defaultZone:http: http://${spring.cloud.client.ip-address}:8761/eureka/

springcloud-service:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    ConnectTimeout: 250 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数

# 该参数用来开启重试机制，它默认是关闭的
spring.cloud.loadbalancer.retry.enabled: true


# 开启feign熔断器机制
feign:
  hystrix:
      enabled: true

# 断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

spring:
  application:
    name: springcloud-consumer  #服务名

